### ISSUE TITLE
gotta transfer code when new page open so you dont need to run again

### ISSUE THREAD

**Issue by CoderBoyCodes** [ijustescapedyesterday/Blooket-Hacks-2023#13]

**Comment by ijustescapedyesterday** [comment]
when you attach it on dashboard.blooket.com, you'll have to reattach it again at play.blooket.com, this is because they are two different websites. think of it as you inject a userscript into google.com, but then go to youtube. It won't stay unless you use some kind of extension or reinject it again

**Comment by CoderBoyCodes** [comment]
Maybe make a loop that keeps running in the domain blocked, that basically
sends a reactivation to a server, asks them to send again on a website that
includes blocked.play, and using this we can transfer code
