### ISSUE TITLE
Doesn't work in game

### ISSUE THREAD

**Issue by Natekalusa** [ijustescapedyesterday/Blooket-Hacks-2023#9]
The GUI only works in the main menu of blooket. When in game, nothing happens. i'm using it as a bookmarklet. my school has blocked the inspect element, so if you can make a bookmarklet, that would be great!

**Comment by ijustescapedyesterday** [comment]
Hello there!

I'm sorry to hear that you're having trouble using the GUI in Blooket. It's possible that the bookmarklet you're using may not work properly in-game due to security restrictions in place at your school, or that you imported it incorrectly. 

However, I have a suggestion that might work for you. Instead of using a bookmarklet, have you considered using a browser extension? There are many browser extensions available that allow you to customize web pages, and some of them might work better for your needs than a bookmarklet.

If browser extensions are also blocked, you could try using another browser (if you were using chrome, use edge, which would let you inspect).

Please provide more detail on the issue so I can know exactly what happened and made adaptations as soon as possible.
